apiVersion: v1
kind: Secret
metadata:
  name: assisted-deployment-pull-secret
  namespace: assisted-installer
stringData:
  .dockerconfigjson:
# Red Hat pull secret for images
# ..redacted.. 
  type: kubernetes.io/dockerconfigjson
