apiVersion: v1
kind: Secret
metadata:
  name: assisted-deployment-ssh-private-key
  namespace: assisted-installer
stringData:
  ssh-privatekey: |-
# Private SSH key for hive use in deployment see ClusterDeployment manifest for public  
# ..redacted..
type: Opaque

